aamks/aamks

evac/worker.py

Updating obstacle processing related to new object type - fire.

bug in processing obstacles

---

include.py
montecarlo/cfast_mcarlo.py

Revert "Stable"

---

montecarlo/cfast_mcarlo.py
rescue_module/rescue.py
rescue_module/rescue_old.py

Fire curve $\dot{Q}(t)$ is now expressed as a class of continuous functions instead of a set of discrete data points.
Resolves #116 and includes an implementation of #69's solution.

Issue #116 continuous hrr func

---

evac/worker.py
gui/form.php
gui/inc.php
gui/lib.form.php
montecarlo/cfast_mcarlo.py
rescue_module/rescue.py

Rescue sub-model fields are clustered in the category. Also detection time bug when two or more detectors went off is fixed along with those changes.
Fix #126 and temporarily fix #127.

Issue #126 #127

---

evac/worker.py
fire/partition_query.py
gui/simulations.php
installer/sql.sql
manager/manager.py
manager/results_collector.py
results/beck_new.py

Logging total heat released in fire (from CFAST `cfast_compartments.csv` output file) added. Plots for single and comparison modes are available in Summary.
Resolves #123.

Issue #123 total heat

---

gui/halt.php
gui/simulations.php
results/beck_new.py

Changes in manage jobs mainly. Convergence indicator, improved layout and functionality and individual risk RMSE added to the summary and data.txt.

Issue #138 convergence

---

montecarlo/cfast_mcarlo.py

Resolves #151 and covers all possible bugs of this kind in stairwells.

staircase openings

---

evac/worker.py
gui/ajax.php
gui/animator/anim.php
gui/animator/index.php
gui/animator/js/animator.js
gui/css/aamks.css
gui/js/fancyTable.js
gui/js/utils.js
installer/sql.sql
results/beck_anim.py

Create a new look of single simulation page, added sorting to animations table

Issue #79 animator view

---

gui/animator/js/animator.js
gui/halt.php
gui/inc.php
gui/js/utils.js
gui/login.php
installer/play.sh
results/beck_new.py

* show 'X%' instead of 10X statuses in halt.php
* fix of wrong values in form when user first sign in
* after succesful launch redirect to halt.php
* use https in links
* aproximate integral of PDF of N fatalities to 1 (MC aproximation error)

Fixes of bugs reported by beta-testing team (Oct '23) 

---

evac/worker.py
gui/ajax.php
gui/halt.php

Issue #180 check progress bug

---

evac/worker.py

run_worker deleted - defined twice

---

gui/halt.php
installer/server_install.sh
installer/worker_install.sh
manager/init.py
redis_aamks/manager.py

Most of changes reference to recent redis introduction.
* import optimization
* new set of commands in redis manager for queue
* adding  missing components in installer files
* alteration in output after jobs removal

Set of improvements from testing environment

---

aamks.py
montecarlo/cfast_mcarlo.py
montecarlo/evac_mcarlo.py

Resolves https://github.com/aamks/aamks/issues/191
Also: redundant import removed, not-used parameters included, `params` variable name changed to less ambiguous `results`.

Open door with 1st percentile delay

---

gui/halt.php

Now PHP throws an error trying to locate status 1000 description.

Show 0% when status 1000

---

gui/halt.php

ok not job_id

---

gui/simulations.php
results/beck_new.py

* 95% interval is included in rmse calculations in `results.beck_new`
* SRI index removed from webGUI as misgiving regarding AAMKS applications

CI of 95% included in MC approximation error

---

installer/sql.sql

Status should be integer to be easily queried.

Type of status column in psql

---

evac/rvo2_dto.py
requirements.txt
results/beck_new.py
results/sa.py

In post process 0 rset value is not included in the calculations, where there is no value 0 is return

fix rset time

---

gui/inc.php

Maybe not the most elegant way, but working. 
There's a problem with header in form.php in change_editor():
header("Location: ?edit");

buffering data

---

gui/css/aamks.css
gui/js/utils.js
gui/projects.php

Added button in project to reset scenario, remove records from database and scenario folder except cad and conf.json

Issue #106 scenario reset

---

results/sa.py

Bug was a result of unused code from old `SA_old` class made for previous version. I've cleaned the code - should work well.

Sensitivity analysis bug fixed

---

gui/form.php
gui/lib.form.php
installer/demo/navmesh/conf.json
installer/demo/simple/conf.json
installer/demo/three/conf.json
montecarlo/cfast_mcarlo.py

If window is closed, can be fully opened by reaching temperature or heat flux measuring by its target. Temperature or heat flux value is set by user preferences.

issue 96 - closed windows breaking

---

results/beck_anim.py

Each fire is handled as separate "room".

Handle multiple fires

---

results/beck_new.py

Logger defined at the beginning of the file prevents its classes import into other scripts.

move logger under main clause

---

gui/login.php

Removed 'reset_email' from SESSION, added verification for new password

update reset form

---

installer/local_install.sh
installer/server_install.sh
installer/worker_install.sh

1. Switch to `dev` branch removed.
2. Remove aamks repo and clone it again in any case of installation launch.
3. Since we abandoned https cluster in favor of local network we share the same aamks repo from server to nodes
Resolves #279

Install default branch

---

gui/access.php
gui/ajax.php
installer/sql.sql

Resolves #298.
Since the feature requires admin's action anyway it is commented in `gui.ajax.ajaxLaunchSimulation()` - more smooth solution would be more than welcome.

Check user authorization before launch

---

evac/worker.py

vestibule bugfix pt. 2

---

montecarlo/cfast_mcarlo.py

targets for regular door only

---

geom/cfast_importer.py
montecarlo/evac_mcarlo.py

Intersections between floors are restored.
Resolves #353

OrderedDict update instead concatenation and cleaning
